version: '3.7'

services:
#Client microservice
  client:
    frontend:
      image: yolo-client:1.0.0
      build:
        context: client
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      stdin_open: true
      depends_on: 
        - backend
      networks:
        yolo-app:
          ipv4_address: 172.0.14.2

#Backend microservice
  backend:
    image: yolo-client:1.0.0
    build:
      context: backemd
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: mongodb://yolo:yolo@172.0.14.4:27017
    depends_on:
      - database
    networks:
        yolo-app:
          ipv4_address: 172.0.14.3

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: yolo
      MONGO_INITDB_ROOT_PASSWORD: yolo
    ports: 27017:27014
    networks:
        yolo-app:
          ipv4_address: 172.0.14.4

volumes:
  mongo_db:
  
networks:
  yolo-app:
    ipam:
      driver: default
      config:
        - subnet: 172.0.14.0/16