version: '3.7'

services:
#MONGO DB microservice
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    command: mongod --port 27017
    ports:
      - '27027:27027'
    volumes:
      - mongo_db:/data/db
    networks:
      - yolo-app

#Client microservice
  client:
    container_name: client_container
    build: .
    image: yomziee/yolo-client:1.0
    working_dir: /app/client
    command: npm start
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - yolo-app

#Backend microservice
  backend:
    container_name: backend_container
    build: .
    image: yomziee/yolo-backend:1.0
    working_dir: /app/backend
    command: npm start
    ports:
      - 5000:5000
    links:
      - mongo_db
    depends_on:
      - mongo_db
    networks:
      - yolo-app

volumes:
  mongo_db:
  
networks:
  yolo-app:
    driver: bridge